[package]
name = "flappy-lib"
version = "0.1.0"
edition = "2024"

[features]
default = []
debug = ["bevy-inspector-egui"]

[dependencies]
bevy = "0.18.0"
bevy-inspector-egui = { version = "0.36.0", optional = true }
